### ISSUE TITLE
Format Headlines of All Pages

### ISSUE THREAD

**Issue by SurajSanap** [SurajSanap/College.ai-main#10]
The headlines across various pages of the `College.ai` project are inconsistent in terms of formatting. To maintain a cohesive and professional appearance, it's essential to standardize the formatting of headlines across all pages.

Tasks:
-  Review and standardize the formatting of headlines in all pages.
-  Ensure consistency in font size, style, and capitalization.
-  Use appropriate markdown formatting for headlines.
-  Verify that all headlines accurately reflect the content they introduce or summarize.

**Comment by shikham12** [comment]
please assign me this issue

**Comment by lassmara** [comment]
Please assign me this issue
