### ISSUE TITLE
Re-Build USER.py Page

### ISSUE THREAD

**Issue by SurajSanap** [SurajSanap/College.ai-main#118]
There are many issues on the user page. Rebuild it with optimized code.

![image](https://github.com/SurajSanap/College.ai-main/assets/101057653/f4b89459-6ec9-4fe3-8ccc-a49bbf3e59da)

**Comment by malhotramoulie** [comment]
Hi @SurajSanap 
Can u pls assign me this code
I would like to solve this issue

**Comment by Shraman-jain** [comment]
@malhotramoulie are you rebuilding the whole user.py ??

**Comment by malhotramoulie** [comment]
yes
Its taking a while will submit it but today evening

**Comment by Shraman-jain** [comment]
okay no problem

**Comment by malhotramoulie** [comment]
so I have proposed the changes in the menu folder with the file name newuser.py so pls check

**Comment by Shraman-jain** [comment]
@malhotramoulie Have you raised the PR request?
