### ISSUE TITLE
Add More Examples to Prompt Example Page and Enhance its Format

### ISSUE THREAD

**Issue by SurajSanap** [SurajSanap/College.ai-main#13]
The current Prompt Example page provides a few examples for users to interact with. To make it more comprehensive and user-friendly, we need to add more examples and enhance the formatting. This will help users better understand how to interact with the application and utilize its features effectively.

Tasks:

-  Add additional examples to the Prompt Example page, covering a wider range of use cases.
-  Ensure that each example is well-explained and provides clear instructions on how to use it.
-  Improve the formatting of the page to make it more visually appealing and easier to navigate.
-- Use headings and subheadings to organize different sections.
-- Add bullet points or numbered lists for clarity.
-- Include code snippets or sample inputs/outputs where relevant.
- Ensure consistency in style and format across all examples.

**Comment by TushtiSavarn** [comment]
Hi @SurajSanap **Proposal for Enhancing Prompt Example Page**

**Issue**: Add More Examples to Prompt Example Page and Enhance its Format 

**Objective**:
The current Prompt Example page lacks comprehensiveness and user-friendliness. By adding more examples and improving the formatting, we aim to provide users with a better understanding of how to interact with the application and utilize its features effectively.

**Tasks**:

1. **Add Additional Examples**:
   - We will add a wider range of examples covering various use cases to the Prompt Example page.
   - Each example will be well-explained and provide clear instructions on how to use it.

2. **Improve Formatting**:
   - We will enhance the formatting of the page to make it visually appealing and easier to navigate.
   - This will involve organizing different sections with headings and subheadings.
   - Bullet points or numbered lists will be used for clarity.
   - Relevant code snippets or sample inputs/outputs will be included where applicable.

3. **Ensure Consistency**:
   - We will maintain consistency in style and format across all examples to provide a cohesive user experience.

**Implementation Plan**:

1. **Gathering Additional Examples**:
   - Review existing examples and identify gaps in coverage.
   - Brainstorm and collect new examples to fill these gaps.
   - Ensure that each example demonstrates a unique aspect or feature of the application.

2. **Drafting Clear Instructions**:
   - Write clear and concise instructions for each example, guiding users on how to interact with the application.
   - Include step-by-step explanations to assist users in understanding the process.

3. **Formatting and Organization**:
   - Utilize headings and subheadings to organize different sections based on the examples' themes or functionalities.
   - Incorporate bullet points or numbered lists to break down complex processes into manageable steps.
   - Integrate code snippets or sample inputs/outputs within the examples to provide a visual representation of the interactions.

**Conclusion**:
Enhancing the Prompt Example page will significantly improve user experience and usability. By adding more examples and improving formatting, users will have a clearer understanding of how to interact with the application. This proposal outlines a systematic approach to achieving these objectives within a reasonable timeline. 

Hence  kindly assign me this task under GSSOC'24 as a contributor

**Comment by SurajSanap** [comment]
@TushtiSavarn ✅

**Comment by TushtiSavarn** [comment]
@SurajSanap  I have updated prompt page . Kindly review the linked pull request .Thank You
