### ISSUE TITLE
Feature: Add Resources Section for Improving Skills of Students

### ISSUE THREAD

**Issue by sreevidya-16** [SurajSanap/College.ai-main#130]
# Description:

I want to add a section on the left side of our website that lists resources for each skill required for job applications. This will help students identify and learn any missing skills they need for job applications. The resources should be categorized by skill and include links to tutorials, courses, articles, and other learning materials.

@SurajSanap, Could you please assign this issue to me under GSSOC'24

**Comment by sreevidya-16** [comment]
@SurajSanap, Could you please assign this issue to me under GSSOC'24

**Comment by SurajSanap** [comment]
This functionality is already in resume analyzer program. Thanks for your interest in this project.
