### ISSUE TITLE
Update README File with New Enhancements

### ISSUE THREAD

**Issue by SurajSanap** [SurajSanap/College.ai-main#18]
The College.ai project has recently been enhanced with new contributions and functionalities. We need to update the README file to reflect these changes accurately. This will help new users and contributors understand the current state of the project and its capabilities.

Tasks:
- Add new Screenshot.
-  Review all recent contributions and new functionalities added to the project.
-  Update the README file to include new sections or modify existing ones as needed.
-  Ensure the README file provides a clear and comprehensive overview of the project, including:

- [ ] Introduction
- [ ] Features and functionalities
- [ ] Dependencies
- [ ] Installation instructions
- [ ] Usage guidelines
- [ ] Folder structure
- [ ] Contribution guidelines
- [ ] License information

**Comment by lassmara** [comment]
please assign me this issue

and also can you add label level3?

**Comment by SurajSanap** [comment]
Hi @lassmara,

GSSoC instructed not to add level labels to issues related to documentation.

**Comment by aasthakourav20** [comment]
Hey @SurajSanap , Kindly assign this issue to me under GSSoc'24
