### ISSUE TITLE
Integration of LLM Application Using Google Gemini Pro and LangChain for Multiple PDF Document Handling

### ISSUE THREAD

**Issue by revanth1718** [SurajSanap/College.ai-main#21]
To further enhance the capabilities of the platform, I propose integrating a new feature that utilizes Google Gemini Pro and LangChain to handle multiple PDF documents. This feature will employ FAISS vector embeddings to efficiently manage and query the content of multiple PDFs.

I am Participating in GSSOC'24.

**Comment by SurajSanap** [comment]
Hi @revanth1718,

Thank you for your suggestion and for taking the time to propose an enhancement to the `College.ai` platform. We truly appreciate your engagement and interest in improving our project.

We are pleased to inform you that the feature you described is already implemented in our project `(Ask_To _PDF page)`.
If you have any additional ideas or further enhancements in mind, we would love to hear them. Your contributions are highly valued, and we are always open to improving and expanding the platform.

Once again, thank you for your input and for being an active member of our community.

**Comment by revanth1718** [comment]
![Screenshot (560)](https://github.com/SurajSanap/College.ai-main/assets/109272714/fbc0a8d0-926a-481c-ad0a-417c16a5b2da)
there is an issue in your app!!!

**Comment by revanth1718** [comment]
Is your app have the capability to handle multiple PDF documents.

**Comment by SurajSanap** [comment]
Hi @revanth1718 ,
We use multiple PDFs for training on my end, but the app is currently unable to process and generate data during queries. It appears there's an issue that needs to be addressed. _Thank you for bringing this to my attention._ You can go ahead and start working on it.

![image](https://github.com/SurajSanap/College.ai-main/assets/101057653/ab4b97dc-b842-4d88-a3e7-7bf7191fd94e)

**Comment by SurajSanap** [comment]
Additionally, I suggest you clone the repository again as we have made some small updates to it.

**Comment by revanth1718** [comment]
ok sure

**Comment by Rajendran2201** [comment]
Hey @SurajSanap, 

I can work on this issue as I am familiar with developing chatbots and PDF parsing. 
Can you assign me this issue under Gssoc'24?

Thank you!

**Comment by Kirti-Pant** [comment]
@SurajSanap  please assign this task to me?
