### ISSUE TITLE
Enhance Readme file 

### ISSUE THREAD

**Issue by aasthakourav20** [SurajSanap/College.ai-main#24]
A README file is crucial because it serves as the entry point for anyone interacting with your project. It provides essential information about what the project is, how it's structured, and how to use it. Think of it as the first impression someone gets when they encounter your project. A well-written README can save time and frustration for both you and others by clearly outlining the purpose of the project, installation instructions, usage examples, and any other pertinent details. It sets expectations, facilitates collaboration, and helps maintainers and users alike understand and engage with the project more effectively. In essence, a README is the user manual for your project, and investing time in crafting it can greatly enhance the overall experience for everyone involved.

Please assign this issue to me under GSSoC'24

**Comment by SurajSanap** [comment]
Issue has already been raised #18
