### ISSUE TITLE
 Enhancing Home page,

### ISSUE THREAD

**Issue by lassmara** [SurajSanap/College.ai-main#36]
i want to enhance the Home page and Do some changes in it  , can you assign me this under GSSOC?

**Comment by SurajSanap** [comment]
Hey @lassmara,

Thanks again for your interest in our project. You can start your work and make sure to add necessary details like screenshots.

**Comment by lassmara** [comment]
Hi @SurajSanap , I found this background more attractive for your page, let me know your views so that i can pull request.

<img width="959" alt="back3" src="https://github.com/SurajSanap/College.ai-main/assets/136198623/6eb24d75-0303-46c9-ae6e-fa49abafcecd">
<img width="956" alt="back2" src="https://github.com/SurajSanap/College.ai-main/assets/136198623/916a4dcb-38ff-4698-9e95-c46701aaf5bb">
<img width="959" alt="back1" src="https://github.com/SurajSanap/College.ai-main/assets/136198623/cdecfba7-3d1b-4eeb-8510-6e3ddcf5fd86">

**Comment by lassmara** [comment]
before , for your refernce
<img width="955" alt="back_before" src="https://github.com/SurajSanap/College.ai-main/assets/136198623/7ddefd72-d03b-44f0-87ca-65c593521cca">

**Comment by SurajSanap** [comment]
Hey @lassmara, could I have your LinkedIn profile? I’d like to give a **shoutout** to the College.ai project contributors on LinkedIn.

**Comment by lassmara** [comment]
Thats great 😊 ,thanks !

https://www.linkedin.com/in/sai-sruthi-maraboina?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app
