### ISSUE TITLE
Design a Logo for the project COLLEGE.AI

### ISSUE THREAD

**Issue by MehtabAsHellic** [SurajSanap/College.ai-main#38]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab

**Comment by SurajSanap** [comment]
Hi Mehtab (@MehtabAsHellic ),
Thank you for your interest in contributing to our project as part of GSSoC. We have reviewed your portfolio and would love to assign this issue to you. Our team will review your work once submitted.

**Comment by MehtabAsHellic** [comment]
@AbhiDiva96 should I design the logo color according to the current theme of the https://collegeai.streamlit.app/,
or you want it as new branding identity

**Comment by MehtabAsHellic** [comment]
![Collegeai](https://github.com/SurajSanap/College.ai-main/assets/101495398/78deceff-9b51-4550-b751-d42a042fbbfe)

**@SurajSanap Let me know your thoughts and we can iterate with the design and make more better with it.**

**Comment by raunakcy** [comment]
I would like to work on this issue. Kindly assign me the issue.

**Comment by MehtabAsHellic** [comment]
> ![Collegeai](https://private-user-images.githubusercontent.com/101495398/335876706-78deceff-9b51-4550-b751-d42a042fbbfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczOTE4MTcsIm5iZiI6MTcxNzM5MTUxNywicGF0aCI6Ii8xMDE0OTUzOTgvMzM1ODc2NzA2LTc4ZGVjZWZmLTliNTEtNDU1MC1iNzUxLWQ0MmEwNDJmYmJmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwNTExNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzVlNmVmZjhkNzFlYTc2MDk4NDA5MzcyYjA2NzNhZTg3ODdlNGI3M2FkNWQwMWIzNzZhMTBiYTNjZjAyMGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-XprcgydqjXRhXyb4aoXuopPOtoeA9kICm5OMah4_co)
> 
> **@SurajSanap Let me know your thoughts and we can iterate with the design and make more better with it.**

any comment @SurajSanap

**Comment by 2004khushig** [comment]
Hi!
I am an ardent user of Canva and a part of design team of my club. I would really like to contribute and give my perspective for the logo for this project.

**Comment by raunakcy** [comment]
kindly  assign me  this issue.
