### ISSUE TITLE
Add Contribution.md

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [SurajSanap/College.ai-main#4]
Hey @SurajSanap ,
To streamline the contribution process and make it easier for new contributors to get involved, it's important to have clear and detailed contribution guidelines. A CONTRIBUTING.md file outlines the steps and best practices for contributing to the project, ensuring consistency and high-quality contributions.
Please assign me this issue

**Comment by SurajSanap** [comment]
go ahead. @Santhosh-Siddhardha
