### ISSUE TITLE
Add feature of projects and research papers where students can get idea of making their major or minor projects.

### ISSUE THREAD

**Issue by SurajSanap** [SurajSanap/College.ai-main#40]
@SurajSanap  We can add feature of projects and research papers where students can get idea of making their major or minor projects and also can get reference of research paper with the feature of plagarism check. We can implement it using API integration and store the projects in database.

_Originally posted by @zeelshah1805 in https://github.com/SurajSanap/College.ai-main/issues/12#issuecomment-2134915594_

**Comment by zeelshah1805** [comment]
@SurajSanap I would like to contribute.

**Comment by SurajSanap** [comment]
Thanks. Go ahead.

**Comment by zeelshah1805** [comment]
@SurajSanap Thank you for your encouragement. I'll start working on it and will keep you in loop.

**Comment by Kirti-Pant** [comment]
@SurajSanap  can I work on this project under GSSoC'24?

**Comment by adityasingh-0803** [comment]
@SurajSanap i can work under gssoc
