### ISSUE TITLE
The account section of the app lacks a logout feature. Also it shows an error when we try to log in

### ISSUE THREAD

**Issue by Amishachoudhary22** [SurajSanap/College.ai-main#44]
<img width="837" alt="Screenshot 2024-06-02 at 10 55 19 PM" src="https://github.com/SurajSanap/College.ai-main/assets/103454929/eedbae16-7018-4e4f-8738-c15c8a9a2c02">

**Comment by Shubham-Zone** [comment]
@SurajSanap please assign this to me i am GSSOC'24 contributor and have 2+ year of experience in development
