### ISSUE TITLE
Adding Contact us page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [SurajSanap/College.ai-main#52]
I will add a contact us page for the website .

**Comment by khushi-igupta** [comment]
Hello @Ayushmaanagarwal1211 , I am GSSOC'24 contributor. Kindly assign me this issue.

**Comment by SurajSanap** [comment]
Hi @Ayushmaanagarwal1211, The functionality of this web app is very simple, so there's no need for a `'contact us`' page. Additionally, my account links are already available on the '`about page`'. Thank you for addressing this issue.
