### ISSUE TITLE
Feature - Integrate tooltips

### ISSUE THREAD

**Issue by Abhay182005dat** [SurajSanap/College.ai-main#63]
Greetings Sir !!

I would like to add a introductory tool tips with the help of steam lit which would make the users feel comfortable while starting with the website / Web ap experience.

I hope this Feature will be very much useful and would look nice . :)

Thank You

**Comment by SurajSanap** [comment]
Hi @Abhay182005dat bro, This web app is very simple to understand. So I don't think any tips are required here. Thank you for addressing this issue.
