### ISSUE TITLE
[FEAT]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [SurajSanap/College.ai-main#65]
### Currently, there is no issue template for this repo, so I want to add it which will look like this 👇

![image](https://github.com/govind-kumarr/simple_rag_dashboard/assets/73957207/1a966085-fdc3-4abf-98af-af40b9fd34d7)

- ### Also I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
### Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/govind-kumarr/simple_rag_dashboard/assets/73957207/bc784050-74d3-4270-862d-d36ae6df0c4d)
 
- I also saw that one PR was merged earlier related to this but there are no changes at all ( might be there will be bugs). So I am here to fix that.

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by SurajSanap** [comment]
Hi @TonyStark-47, the developement of this web app is almost done. So we don't require any` issue template` right now.Thanks for your issue.

**Comment by TonyStark-47** [comment]
Ok, Best of luck!

**Comment by TonyStark-47** [comment]
Ok, Best of luck!
