### ISSUE TITLE
Feat: Adding a better navbar for the website with on hover expansion properties

### ISSUE THREAD

**Issue by arpy8** [SurajSanap/College.ai-main#7]
The current default navbar is not very impressive, so I propose adding a third-party navbar called On-Hover-Tabs.

Something like this 
![](https://raw.githubusercontent.com/Socvest/streamlit-on-Hover-tabs/main/img/demonstration-on-hover.gif)

For more info:
https://github.com/Socvest/streamlit-on-Hover-tabs/

**Comment by SurajSanap** [comment]
Go ahead.
