### ISSUE TITLE
Spelling mistake in readme file

### ISSUE THREAD

**Issue by NidhiTornekar** [SurajSanap/College.ai-main#79]
There is a spelling mistake in the readme file. It should be "Contributing" instead of "Contibuting".
![ss6](https://github.com/SurajSanap/College.ai-main/assets/121748841/a68fb4a1-5d10-4e1f-a9c7-2f34cb65a379)

Please assign me this issue under GSSOC 2024

**Comment by Shubham-Zone** [comment]
@SurajSanap please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
