### ISSUE TITLE
Enhanced Authentication Features - Implement OAuth Login

### ISSUE THREAD

**Issue by SurajSanap** [SurajSanap/College.ai-main#8]
![image](https://github.com/SurajSanap/College.ai-main/assets/101057653/f9b65403-b1ca-411e-ab7d-22ea0389a93f)

**Description**:
Currently, the application only supports traditional email/password authentication. Enhance the authentication system by integrating OAuth login, allowing users to log in via their Google accounts or other OAuth providers. This will improve user experience and provide an additional authentication option.

**Tasks**:
1. Research OAuth authentication methods and providers, focusing on Google OAuth for initial implementation.
2. Implement OAuth authentication flow for Google accounts using a library such as OAuthlib or Authlib.
3. Add a "Login with Google" button to the login page, linking to the OAuth authentication endpoint.
4. Handle OAuth authentication callback to retrieve user information and create a new account or authenticate an existing user.
5. Update user session management to support both email/password and OAuth login methods.
6. Test the OAuth login functionality thoroughly to ensure seamless integration and security.
7. Update documentation and user instructions to include information on OAuth login.

Sure, here's the grammatically correct version:

---
At the end, we expect that users will need to log in first before they can access the web functionalities.

**Comment by lassmara** [comment]
Please assign me this issue

**Comment by lassmara** [comment]
can you please change the label to level3?
