### ISSUE TITLE
Update required Readme.md 

### ISSUE THREAD

**Issue by Meetjain1** [SurajSanap/College.ai-main#80]
Curently readme.md file is good , But it can be more fascinating If we add contributors section at the bottom of the file and some allignment fix , adding animated emojis and also fix the gif placed in the readme. @SurajSanap assign this issue to me I will add it ,
I am working under gssoc. Thanks

**Comment by Shubham-Zone** [comment]
@SurajSanap please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
