### ISSUE TITLE
THEME FEATURE

### ISSUE THREAD

**Issue by SDprogramer** [SurajSanap/College.ai-main#83]
![Screenshot 2024-06-08 170909](https://github.com/SurajSanap/College.ai-main/assets/155221332/e006d348-e903-448d-b76d-fc8dbfb8afb3)

Like when we are clicking the theme change button it does not changes it unless we refresh the page so i want to make it automatic and i have some other issues in the code snippets also.

please assign this issue to me @SurajSanap and please add the required labels.

**Comment by Shubham-Zone** [comment]
@SurajSanap please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development

**Comment by SDprogramer** [comment]
@Shubham-Zone we can collab in this ?? Will you do it

**Comment by SurajSanap** [comment]
It work on double click.

**Comment by lassmara** [comment]
can i also contribute in this?

**Comment by SDprogramer** [comment]
@lassmara yes i would like to collaborate with you i don't have a problem

soumyadeep_dey00 my discord id ping me there and we can discuss

**Comment by lassmara** [comment]
> @lassmara yes i would like to collaborate with you i don't have a problem
> 
> soumyadeep_dey00 my discord id ping me there and we can discuss

hi, thankyou but, i can start contributing only if @SurajSanap assigns me .
