### ISSUE TITLE
Shifting the theme button

### ISSUE THREAD

**Issue by lassmara** [SurajSanap/College.ai-main#87]
can you please assign this under gssoc, so that i can make a pull request?
i want to replace the theme buttton , As its not appealing now.after vs before versions are attached below for your reference
![image](https://github.com/SurajSanap/College.ai-main/assets/136198623/311d9857-06ac-4931-a55e-1504ba34755a)

![image](https://github.com/SurajSanap/College.ai-main/assets/136198623/3ed32875-8283-427d-a652-3534897aad6d)

**Comment by SurajSanap** [comment]
Make sure it will work correctly.

**Comment by lassmara** [comment]
We have to enhance the the logic of theme button. issue : THEME FEATURE #83

**Comment by lassmara** [comment]
i want to reopen this issue, there is a bug in code .One function has been removed and we are getting error, i used another approach. Can you please reopen this?
