### ISSUE TITLE
Adding a feature like Question paper analyser would be a great add up to college.ai

### ISSUE THREAD

**Issue by Bharathhh30** [SurajSanap/College.ai-main#89]
Creating a feature using gemini pro-vision to analyse the semester papers of the students and give them similar kind of questions to practice and breifing about the topics covered in the exam paper , as we do before night preps for sem and mid term exams , this tool might save a lot time and would help us guess questions accurately

It gives up time to spend on projects rather than doing the bargains for the Important questions

@SurajSanap Hope you find this effective and guide me through this feature if this excites you !!
Thank You

**Comment by SurajSanap** [comment]
Hi @Bharathhh30,/
Thank you for your interest in this project. After careful consideration, I don't think this idea will be quite beneficial for our current goals. Therefore, I will be closing this issue . Please feel free to share any other ideas you may have in the future.
