### ISSUE TITLE
[Feature]: Want to Add "Coding Contest" Section.

### ISSUE THREAD

**Issue by Shraman-jain** [SurajSanap/College.ai-main#94]
Want to add a coding contest section where the student can get all the information about the upcoming coding contest from various platform like Leetcode, Codechef, GFG , HackerRank. CodeForces etc 
Please assign me this issue under gssoc24

**Comment by Kanika0304** [comment]
Hi, I’m Kanika Sharma, interested in contributing to open source projects. I propose to add a dedicated coding contest section to the website, providing students with comprehensive information about upcoming coding contests from various platforms such as LeetCode, CodeChef, GeeksforGeeks, HackerRank, and CodeForces. This section will include details like contest dates, registration links, and platform-specific information, enabling students to easily access and participate in coding competitions. Could you please assign this issue to me under GSSoC '24?

**Comment by Shraman-jain** [comment]
Hi @Kanika0304 please find some new issue as i have already raised it and willing to work upon it.

**Comment by Kanika0304** [comment]
Ok, Thankyou

**Comment by SurajSanap** [comment]
Hi @Shraman-jain, Thank you for your interest in this project. You can start your work. Please ensure that your work is of high quality and helpful for students.

**Comment by Shraman-jain** [comment]
Sure @SurajSanap
