### ISSUE TITLE
Replacing plain text password storage with "Password Hashing Implementation"

### ISSUE THREAD

**Issue by asrithaMulugoju** [SurajSanap/College.ai-main#99]
### Description

In this implementation, the security of the authentication system is enhanced by replacing plain text password storage with hashed passwords using the `werkzeug.security` library. During the signup process, passwords are hashed with `generate_password_hash` before being stored in the SQLite database. During login, the hashed password is verified using `check_password_hash`. This approach ensures that user passwords are securely stored, protecting them from potential breaches and unauthorized access. Additionally, the code includes improved error handling and proper closing of the database connection to ensure robustness and reliability of the application.

I would love to work on this feature, could you please assign this work with gssoc, level1/level/2/level3 based on feature involvement @SurajSanap

**Comment by SurajSanap** [comment]
Hi @asrithaMulugoju, Thank you for your interest in this project. Currently, the authentication page is not well programmed, so it may be a bit challenging for you to handle it. You can start your work now. Please ensure that your work is of high quality and helpful for students.

**Comment by asrithaMulugoju** [comment]
Sure sir.
Thank you for your response!

**Comment by Premonvitha-Sai** [comment]
Hi @SurajSanap can you assign me I want to work on this issue.
